export const menuItems = [
  {
    id: 1,
    name: 'Classic Espresso',
    description: 'Rich, bold double shot pulled from premium Arabica beans',
    price: 3.50,
    category: 'hot',
    gradient: 'linear-gradient(135deg, #1a0e00 0%, #3e2723 50%, #5d4037 100%)',
  },
  {
    id: 2,
    name: 'Caramel Latte',
    description: 'Smooth espresso blended with steamed milk and caramel drizzle',
    price: 5.50,
    category: 'hot',
    gradient: 'linear-gradient(135deg, #2c1810 0%, #6d4c41 50%, #c9a96e 100%)',
  },
  {
    id: 3,
    name: 'Vanilla Cappuccino',
    description: 'Classic cappuccino with a hint of Madagascar vanilla',
    price: 5.00,
    category: 'hot',
    gradient: 'linear-gradient(135deg, #3e2723 0%, #8d6e63 50%, #d7ccc8 100%)',
  },
  {
    id: 4,
    name: 'Iced Mocha',
    description: 'Dark chocolate espresso over ice with whipped cream',
    price: 6.00,
    category: 'iced',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #4e342e 50%, #8d6e63 100%)',
  },
  {
    id: 5,
    name: 'Cold Brew',
    description: '18-hour steeped cold brew, smooth and naturally sweet',
    price: 4.50,
    category: 'iced',
    gradient: 'linear-gradient(135deg, #0d0d0d 0%, #263238 50%, #455a64 100%)',
  },
  {
    id: 6,
    name: 'Matcha Latte',
    description: 'Ceremonial grade matcha whisked with oat milk',
    price: 5.50,
    category: 'specialty',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #388e3c 50%, #66bb6a 100%)',
  },
  {
    id: 7,
    name: 'Hazelnut Frappe',
    description: 'Blended hazelnut coffee with cream and cocoa dusting',
    price: 6.50,
    category: 'blended',
    gradient: 'linear-gradient(135deg, #4e342e 0%, #795548 50%, #bcaaa4 100%)',
  },
  {
    id: 8,
    name: 'Affogato',
    description: 'Hot espresso poured over artisan vanilla gelato',
    price: 7.00,
    category: 'specialty',
    gradient: 'linear-gradient(135deg, #2d1b00 0%, #5d4037 50%, #efebe9 100%)',
  },
];

export const menuCategories = [
  { key: 'all', label: 'All' },
  { key: 'hot', label: 'Hot Drinks' },
  { key: 'iced', label: 'Iced Drinks' },
  { key: 'blended', label: 'Blended' },
  { key: 'specialty', label: 'Specialty' },
];